### ISSUE TITLE
categories option is unavailable due to @onready issue

### ISSUE THREAD

**Issue by tvenclovas96** [Portponky/better-terrain#102]
The categories option is missing from the terrain setup window. Upon opening the window an error pops up in the console
 `res://addons/better-terrain/editor/TerrainProperties.gd:42 - Cannot call method 'show' on a null value.`

The source of this error is that the control nodes of the popup are referenced via `@onready` variables, and ready hasn't been called yet when the variables are accessed. This seems like functionality that somehow got affected by 4.3 changes.

![image](https://github.com/user-attachments/assets/53458015-4497-48fb-aeb6-76b059f19b42)
![image](https://github.com/user-attachments/assets/6e422e36-a3b7-4f3b-857f-ed60da534913)

**Comment by Portponky** [comment]
Oops, that got overlooked during testing. Easy fix, will have it sorted very soon.

**Comment by Portponky** [comment]
Fixed on main and 4.2. I've updated the asset lib version but that might take a bit to be accepted. This should fix the problem.
