### ISSUE TITLE
Offset grid setup somehow missing bottom right corner

### ISSUE THREAD

**Issue by Supamiu** [Portponky/better-terrain#105]
Hi, I followed your tutorial from YouTube (https://www.youtube.com/watch?v=eUUDxg5MU3w) regarding dual grid setup.

I'm using latest release from AssetLib.

Here are my terrain pairing bits:
![image](https://github.com/user-attachments/assets/67f2582b-a73e-427d-9708-f03baef918b7)

But when painting terrain, the bottom-right corner sometimes doesn't show up and I have no idea how this is possible:
![Godot_7X52t7Sov2](https://github.com/user-attachments/assets/e44449e9-a351-420b-842c-1a1913f91b01)

I've tried replicating it with other terrain shapes and it's always the bottom-right corner that has this issue.

**Comment by Portponky** [comment]
That's weird. Looks like it should work, and it definitely shouldn't be placing an empty cell. Can you upload an example project for this?

**Comment by Supamiu** [comment]
Now that's interesting, I cannot reproduce in a minimal setup project, I'll investigate further and report my findings here

**Comment by Supamiu** [comment]
Was due to changes from https://github.com/Portponky/better-terrain/issues/62, closing this but maybe it'll help someone with the same needs (I don't need cleanup anymore with dual tilemap setup tho)
