### ISSUE TITLE
Add ability to set preview icon

### ISSUE THREAD

**Issue by univeous** [Portponky/better-terrain#19]
Adding the ability to set a preview icon for terrain would greatly enhance the user experience.
This includes Adding a button at the toolbar to enter Select Icon mode to set the preview icon for terrain and show an icon preview in the Tree.
A rough prototype: (there is no new button in the toolbar but you got my point)

![image](https://github.com/Portponky/better-terrain/assets/40604180/58108115-bce4-4178-bacb-37fc8900d292)

**Comment by torcado194** [comment]
I think this is a great idea. I'd be happy to work on this.

I think it would also be cool to alternatively use a tile in the TileSet as the icon.

**Comment by univeous** [comment]
Yeah sure, that's exactly what mean. Add a button to enter set icon mode and select an icon from the tileset image. Kind of like the behavior that used to exist in Godot 3. Sorry I wasn't very clear.

**Comment by Portponky** [comment]
Implemented by https://github.com/Portponky/better-terrain/pull/27 now available on master
