### ISSUE TITLE
"BetterTerrain" not declared in current scope. 

### ISSUE THREAD

**Issue by glassramen** [Portponky/better-terrain#23]
![ScreenCap](https://github.com/Portponky/better-terrain/assets/37496337/6fd606e2-9295-4941-b07d-0ccb9204bf7f)

I tried loading it in a project already in progress, along with attempting to load it in a fresh one. In both instances it results in the picture above. It's throwing "not declared" every time it calls for BetterTerrain. 

The first instance of the error is as you can see line 63 of TerrainProperties.gd. 

The visually identifiable issues these errors cause are that when selecting the tilemap section the buttons your addon are supposed to provide do not appear, and as far as I can tell there are no changes to the terrain system from normal godot functionality. 

I'm going to do a little bug hunting to see if I (even with my limited skill) can figure out a solution

**Comment by Portponky** [comment]
Is the plugin activated in the plugins tab of project settings?

Have you tried restarting Godot? Always a good idea after changing the plugin settings, because it's a little temperamental about autoloads.

**Comment by glassramen** [comment]
Yes, I ensured it was active. I have also restarted Godot after activating and it resulted in the same. I'm assuming it's got to be something only happening for me as I'm ~_special_~ and always encounter strange errors that most others don't. Other things I've ruled out are things like windows being over protective, since it's in a slave drive rather than the main in a directory that isn't considered protected. I'm fairly certain there isn't anything external doing any funny business with Godot, so while I'm away from my main PC at the moment, when I boot it up in a bit I'll try grabbing a slightly earlier version of Godot, and maybe a fresh clone of the addon, and see if that fixes it. Maybe it'll just decide that it wants to work and I wont have to do any of that, who knows. 

I'll update you on whether or not I get it going, or if it still has issues.

**Comment by glassramen** [comment]
![Capture](https://github.com/Portponky/better-terrain/assets/37496337/97775667-6a37-4ab8-9779-31c50c5cee6e)
And, unceremoniously, it works now. I can't even say it was due to shutting down or restarting the PC as I had it in hibernation. There are those few errors popping up still but not like before, nor the same errors. Sorry to have seemingly wasted your time.
