### ISSUE TITLE
Terrain list scrolls horizontally on mousewheel when it only has a few terrains 

### ISSUE THREAD

**Issue by Portponky** [Portponky/better-terrain#28]
This, basically:

https://github.com/Portponky/better-terrain/assets/33663279/7ccc633e-a3c2-4c44-b474-5f168a6e4040

Not a biggie but it's quite easy to do by accident. I tried some stuff to fix it, but couldn't quite get it to behave.

**Comment by torcado194** [comment]
Oh, I did notice this once while implementing the grid view and then forgot about it. It's an annoying consequence of the large item size to enforce wrapping, but every alternative I tried had worse downsides.
