### ISSUE TITLE
show currently applied shaders in the terrain tab

### ISSUE THREAD

**Issue by oxixxixo** [Portponky/better-terrain#29]
I've created a tileset using shaders but I can't really see what I'm doing in the terrain tab

![image](https://github.com/Portponky/better-terrain/assets/61514710/a3c53a6b-290a-4697-8d6e-c851d7c3c330)

![image](https://github.com/Portponky/better-terrain/assets/61514710/03a143d2-b72e-4323-b18a-8139b108588c)

Thanks for making such a useful plugin!

**Comment by Portponky** [comment]
Hi, that could definitely be improved. I have no experience applying shaders to tile atlases. I'll give it a shot some time today, but if you have a small example for me to work with, that would help a lot.

**Comment by Portponky** [comment]
Aha, I worked out how to apply shaders to individual tiles, so I will see how easy it is to fix.

**Comment by oxixxixo** [comment]
Here's a godot 4.1 project with a pink shader applied to a tileset incase you could still use it (.godot folder removed).
[shader_tiles.zip](https://github.com/Portponky/better-terrain/files/12209635/shader_tiles.zip)

**Comment by Portponky** [comment]
I believe I have it working. I had to learn a bunch about RenderingServer and how Godot handles materials: 
![image](https://github.com/Portponky/better-terrain/assets/33663279/afbb7998-70d8-4623-9e2e-b5c1dbf3349a)

Will do some testing before pushing it.

**Comment by Portponky** [comment]
This should be fixed on the latest commit a23515216e8b1b927e3b43e9b4bbf273b2b979ac
If you can confirm it works for you, then I will close this ticket. Cheers!

**Comment by oxixxixo** [comment]
seems to work on my end, thanks for the fix
