### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by Vixeliz** [Portponky/better-terrain#3]
Is there any way to set wildcards it's one of my largest gripes with godot 4.0. For example I want the terrain to match with any tile regardless of type.

**Comment by Portponky** [comment]
At the moment, you can only do this by applying every terrain type to every peering bit as needed. This will probably take a very long time.

I'm planning on implementing a grouping feature soon, as it has been a popular request. This should help with wildcards: if you assign all terrain types to the same group, they will all match with each other.

**Comment by Vixeliz** [comment]
Is the grouping feature the same as the pr that has been made? I may use it till you come up with an official solution

**Comment by Portponky** [comment]
I won't be using the PR, but I'll be doing something fairly similar.

**Comment by Vixeliz** [comment]
Fair, do you have any eta by chance ofc fine if not but jw

**Comment by Vixeliz** [comment]
And one other thing I noticed is it doesn't seem possible to delete or clear a cell from code. I tried negative one and it didn't work and ofc higher then that is the actual terrain types.

**Comment by Portponky** [comment]
I'm fairly busy for the next week and a half, but I'll try to find time.

Regarding drawing, the dock/editor uses the same API that the terrain is provided through. Make sure you are using the API correctly - `BetterTerrain.set_cell(tilemap, layer, coord, type)`.

**Comment by Portponky** [comment]
Closing in favor of https://github.com/Portponky/better-terrain/issues/4 which has an implementation of this feature on the `category` branch. Feel free to try that out, but I will be merging it back soon if you don't get time.
