### ISSUE TITLE
Recent Download Does Not Work / Lots of Errors

### ISSUE THREAD

**Issue by jaybaird** [Portponky/better-terrain#35]
After the most recent youtube video, decided to upgrade my Better-Terrain install, but now I can't even get the add-on to load properly.

It appears that Godot thinks all the tscn files are "corrupt" which leads to `dock` being null and crashes the whole thing. 

Here are all the errors:
```
  Unable to open file: res://.godot/imported/MatchTiles.svg-38111e21a893bd8f161311f0d1968a40.editor.ctex.
  Failed loading resource: res://.godot/imported/MatchTiles.svg-38111e21a893bd8f161311f0d1968a40.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/MatchTiles.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/MatchVertices.svg-288fe47ee1089920379407d6abf1a06c.editor.ctex.
  Failed loading resource: res://.godot/imported/MatchVertices.svg-288fe47ee1089920379407d6abf1a06c.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/MatchVertices.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/NonModifying.svg-4d16d471be4a8f1d3ba0c013ff629ee1.editor.ctex.
  Failed loading resource: res://.godot/imported/NonModifying.svg-4d16d471be4a8f1d3ba0c013ff629ee1.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/NonModifying.svg. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:284 - res://addons/better-terrain/editor/TerrainProperties.tscn:60 - Parse Error: 
  Failed loading resource: res://addons/better-terrain/editor/TerrainProperties.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/Decoration.svg-03773e83cc849c7744ecf3d36eee0072.editor.ctex.
  Failed loading resource: res://.godot/imported/Decoration.svg-03773e83cc849c7744ecf3d36eee0072.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/Decoration.svg. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:284 - res://addons/better-terrain/editor/TerrainEntry.tscn:82 - Parse Error: 
  Failed loading resource: res://addons/better-terrain/editor/TerrainEntry.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/EditType.svg-e7b3005c6a8f21d5102295c55b564ad1.editor.ctex.
  Failed loading resource: res://.godot/imported/EditType.svg-e7b3005c6a8f21d5102295c55b564ad1.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/EditType.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/Replace.svg-7654df79fd42fc27133e4d3f81a4d56b.editor.ctex.
  Failed loading resource: res://.godot/imported/Replace.svg-7654df79fd42fc27133e4d3f81a4d56b.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/Replace.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/EditTerrain.svg-f7ee950d68a391de33e4e8ddd76bf2ac.editor.ctex.
  Failed loading resource: res://.godot/imported/EditTerrain.svg-f7ee950d68a391de33e4e8ddd76bf2ac.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/EditTerrain.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/Warning.svg-7bb0ec60ff2da2c7ebdba79b0dcdd006.editor.ctex.
  Failed loading resource: res://.godot/imported/Warning.svg-7bb0ec60ff2da2c7ebdba79b0dcdd006.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/Warning.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/ShuffleRandom.svg-15ee49f7a06c55a1e95e1ed056732dc5.editor.ctex.
  Failed loading resource: res://.godot/imported/ShuffleRandom.svg-15ee49f7a06c55a1e95e1ed056732dc5.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/ShuffleRandom.svg. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:284 - res://addons/better-terrain/editor/Dock.tscn:100 - Parse Error: 
  Failed loading resource: res://addons/better-terrain/editor/Dock.tscn. Make sure resources have been imported by opening the project in the editor at least once.
Add Autoload
  scene/resources/packed_scene.cpp:141 - Condition "nc == 0" is true. Returning: nullptr
  res://addons/better-terrain/TerrainPlugin.gd:12 - Invalid get index 'update_overlay' (on base: 'null instance').
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/Decoration.svg-03773e83cc849c7744ecf3d36eee0072.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/EditTerrain.svg-f7ee950d68a391de33e4e8ddd76bf2ac.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/EditType.svg-e7b3005c6a8f21d5102295c55b564ad1.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/MatchTiles.svg-38111e21a893bd8f161311f0d1968a40.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/MatchVertices.svg-288fe47ee1089920379407d6abf1a06c.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/NonModifying.svg-4d16d471be4a8f1d3ba0c013ff629ee1.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/Replace.svg-7654df79fd42fc27133e4d3f81a4d56b.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/ShuffleRandom.svg-15ee49f7a06c55a1e95e1ed056732dc5.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/Warning.svg-7bb0ec60ff2da2c7ebdba79b0dcdd006.editor.meta'
  :12 - Unknown identifier in expression: 'u_windowSize'.
  Shader compilation failed.
  ./servers/rendering/renderer_rd/shader_rd.h:165 - Condition "!version" is true. Returning: RID()
  ./servers/rendering/renderer_rd/shader_rd.h:165 - Condition "!version" is true. Returning: RID()
  ./servers/rendering/renderer_rd/shader_rd.h:165 - Condition "!version" is true. Returning: RID()
  ./servers/rendering/renderer_rd/shader_rd.h:165 - Condition "!version" is true. Returning: RID()
  Unable to open file: res://.godot/imported/Decoration.svg-03773e83cc849c7744ecf3d36eee0072.editor.ctex.
  Failed loading resource: res://.godot/imported/Decoration.svg-03773e83cc849c7744ecf3d36eee0072.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/Decoration.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/EditTerrain.svg-f7ee950d68a391de33e4e8ddd76bf2ac.editor.ctex.
  Failed loading resource: res://.godot/imported/EditTerrain.svg-f7ee950d68a391de33e4e8ddd76bf2ac.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/EditTerrain.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/EditType.svg-e7b3005c6a8f21d5102295c55b564ad1.editor.ctex.
  Failed loading resource: res://.godot/imported/EditType.svg-e7b3005c6a8f21d5102295c55b564ad1.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/EditType.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/MatchTiles.svg-38111e21a893bd8f161311f0d1968a40.editor.ctex.
  Failed loading resource: res://.godot/imported/MatchTiles.svg-38111e21a893bd8f161311f0d1968a40.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/MatchTiles.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/MatchVertices.svg-288fe47ee1089920379407d6abf1a06c.editor.ctex.
  Failed loading resource: res://.godot/imported/MatchVertices.svg-288fe47ee1089920379407d6abf1a06c.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/MatchVertices.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/NonModifying.svg-4d16d471be4a8f1d3ba0c013ff629ee1.editor.ctex.
  Failed loading resource: res://.godot/imported/NonModifying.svg-4d16d471be4a8f1d3ba0c013ff629ee1.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/NonModifying.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/Replace.svg-7654df79fd42fc27133e4d3f81a4d56b.editor.ctex.
  Failed loading resource: res://.godot/imported/Replace.svg-7654df79fd42fc27133e4d3f81a4d56b.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/Replace.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/ShuffleRandom.svg-15ee49f7a06c55a1e95e1ed056732dc5.editor.ctex.```

**Comment by Portponky** [comment]
Hi, what version of Godot are you using?

**Comment by jaybaird** [comment]
Ya got me, it's 4.2.5 preview, because I've got a pretty large open world tilemap and need the perf improvements.

**Comment by Portponky** [comment]
Try the follow (please make sure your project is backed up first).

* disable the plugin in projects settings
* delete the better-terrain folder
* save the project
* restart Godot
* redownload the plugin (from asset lib or here)
* install as usual (enable plugin, restart)

I think the problem might be related to some of the changes related to uuids that have gone in to the latest 4.2 dev versions, though I am not sure. I use the latest version of the plugin with 4.2 dev5 and it works without any problems.

**Comment by Portponky** [comment]
(hit the close button by accident, lol)

**Comment by jaybaird** [comment]
Will give it a try, thanks!

**Comment by colinwilcox** [comment]
I'm in the same boat. Godot 4.1.stable though. Tried from reinstalling from lib and zip. 

`  Unable to open file: res://.godot/imported/EditType.svg-e7b3005c6a8f21d5102295c55b564ad1.editor.ctex.
  Failed loading resource: res://.godot/imported/EditType.svg-e7b3005c6a8f21d5102295c55b564ad1.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/EditType.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/Replace.svg-7654df79fd42fc27133e4d3f81a4d56b.editor.ctex.
  Failed loading resource: res://.godot/imported/Replace.svg-7654df79fd42fc27133e4d3f81a4d56b.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/Replace.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/EditTerrain.svg-f7ee950d68a391de33e4e8ddd76bf2ac.editor.ctex.
  Failed loading resource: res://.godot/imported/EditTerrain.svg-f7ee950d68a391de33e4e8ddd76bf2ac.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/EditTerrain.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/Warning.svg-7bb0ec60ff2da2c7ebdba79b0dcdd006.editor.ctex.
  Failed loading resource: res://.godot/imported/Warning.svg-7bb0ec60ff2da2c7ebdba79b0dcdd006.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/Warning.svg. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/ShuffleRandom.svg-15ee49f7a06c55a1e95e1ed056732dc5.editor.ctex.
  Failed loading resource: res://.godot/imported/ShuffleRandom.svg-15ee49f7a06c55a1e95e1ed056732dc5.editor.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/better-terrain/icons/ShuffleRandom.svg. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:283 - res://addons/better-terrain/editor/Dock.tscn:100 - Parse Error: 
  Failed loading resource: res://addons/better-terrain/editor/Dock.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/better-terrain/TerrainPlugin.gd:11 - Attempt to call function 'instantiate' in base 'null instance' on a null instance.
  res://addons/better-terrain/TerrainPlugin.gd:31 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.
  res://addons/better-terrain/TerrainPlugin.gd:35 - Invalid call. Nonexistent function 'tiles_about_to_change' in base 'Nil'.
  editor/editor_node.cpp:8195 - Condition "plugins_list.has(p_plugin)" is true.
  res://addons/better-terrain/TerrainPlugin.gd:31 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.
  res://addons/better-terrain/TerrainPlugin.gd:35 - Invalid call. Nonexistent function 'tiles_about_to_change' in base 'Nil'.
  editor/editor_node.cpp:8195 - Condition "plugins_list.has(p_plugin)" is true.
  res://addons/better-terrain/TerrainPlugin.gd:45 - Invalid get index 'visible' (on base: 'Nil').
  res://addons/better-terrain/TerrainPlugin.gd:45 - Invalid get index 'visible' (on base: 'Nil').
  res://addons/better-terrain/TerrainPlugin.gd:45 - Invalid get index 'visible' (on base: 'Nil').
  res://addons/better-terrain/TerrainPlugin.gd:31 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.
  res://addons/better-terrain/TerrainPlugin.gd:35 - Invalid call. Nonexistent function 'tiles_about_to_change' in base 'Nil'.
  res://addons/better-terrain/TerrainPlugin.gd:31 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.
  res://addons/better-terrain/TerrainPlugin.gd:35 - Invalid call. Nonexistent function 'tiles_about_to_change' in base 'Nil'.
  editor/editor_node.cpp:8195 - Condition "plugins_list.has(p_plugin)" is true.
  res://addons/better-terrain/TerrainPlugin.gd:31 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.
  res://addons/better-terrain/TerrainPlugin.gd:35 - Invalid call. Nonexistent function 'tiles_about_to_change' in base 'Nil'.
  editor/editor_node.cpp:8195 - Condition "plugins_list.has(p_plugin)" is true.
  res://addons/better-terrain/TerrainPlugin.gd:45 - Invalid get index 'visible' (on base: 'Nil').
  res://addons/better-terrain/TerrainPlugin.gd:45 - Invalid get index 'visible' (on base: 'Nil').
  res://addons/better-terrain/TerrainPlugin.gd:31 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.
  res://addons/better-terrain/TerrainPlugin.gd:35 - Invalid call. Nonexistent function 'tiles_about_to_change' in base 'Nil'.
  res://addons/better-terrain/TerrainPlugin.gd:31 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.
  res://addons/better-terrain/TerrainPlugin.gd:35 - Invalid call. Nonexistent function 'tiles_about_to_change' in base 'Nil'.
  editor/editor_node.cpp:8195 - Condition "plugins_list.has(p_plugin)" is true.
  res://addons/better-terrain/TerrainPlugin.gd:31 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.
  res://addons/better-terrain/TerrainPlugin.gd:35 - Invalid call. Nonexistent function 'tiles_about_to_change' in base 'Nil'.
  editor/editor_node.cpp:8195 - Condition "plugins_list.has(p_plugin)" is true.`

**Comment by Portponky** [comment]
Have you restarted Godot after enabling the plugin on project settings?

If this isn't just Godot's init order being picky, it looks like a knock on effect from how resource id generation has changed for 4.2, which is messing things up. I'll have a look though when I get the chance.

**Comment by colinwilcox** [comment]
Yeah did a few different iterations of launching with and without it enabled, but that didn't work.

But I cleared out my .godot/imported folder and re-launched and now it works 🤷 
I will test w/ 4.2 later.

**Comment by Portponky** [comment]
Should be fixed in latest asset library version.
