### ISSUE TITLE
Add signal for when apply_terrain_changeset is finished.

### ISSUE THREAD

**Issue by Renari** [Portponky/better-terrain#40]
When drawing large amounts of tiles you will have a noticeable performance impact, my solution for this was to batch draws in small chunks at a time. This only partially solves the problem however, with this solution framerates will stay high but you will have stuttering.

The best solution I can find to this is to use `call_deferred` for `apply_terrain_changeset`. The problem with this is that there is currently no way to know when `apply_terrain_changeset` is done with the dictionary reference you pass it, thus preventing you from clearing the dictionary and loading up the next changeset.

Maybe this is to specific of a use case to be implemented, but figured I'd through up the suggestion.

**Comment by Portponky** [comment]
Hmm, it's a bit messy because there's only one BetterTerrain autoload, so a signal would have to pass the changeset itself. Aside from that, as you call `apply_terrain_changeset` from the main thread, you have control over how exactly it is called, so you could do something like this:

```
var changeset = {valid = false}
var applying_changeset := false

func _ready():
	var paint = {}
	for y in 30:
		for x in 30:
			var coord = Vector2i(x, y)
			paint[coord] = randi() % 2
	
	changeset = BetterTerrain.create_terrain_changeset(tilemap, 0, paint)


func _process(_delta):
	if !applying_changeset and BetterTerrain.is_terrain_changeset_ready(changeset):
		applying_changeset = true
		perform_apply_changeset.call_deferred()


func perform_apply_changeset():
	BetterTerrain.apply_terrain_changeset(changeset)
	print("Applied")


func _exit_tree():
	if changeset.valid:
		BetterTerrain.wait_for_terrain_changeset(changeset)
```

Here it just prints 'Applied', but it could do whatever you like.

**Comment by Renari** [comment]
That makes sense, this is a much cleaner way to approach it.
