### ISSUE TITLE
Installing via asset library problem

### ISSUE THREAD

**Issue by mickeyordog** [Portponky/better-terrain#47]
I think there might be a slight issue with how you set up the plugin download through the Godot AssetLib tab. As you can see from the screenshot, it tries to add a license and readme to my project's root res directory, instead of in the addons folder.
![image](https://github.com/Portponky/better-terrain/assets/36612632/92e09703-4b91-4b24-b791-1a796715aa41)

**Comment by Portponky** [comment]
I don't believe I can configure that. The asset library just takes a git repo and commit hash, and it requires that a LICENSE.md is present. There's no way I can see to exclude files. Does anyone know a way of making this behave well?

**Comment by mempler** [comment]
By any chance, can you upload from a specific branch? If so, you can create a separate branch called `asset-library-release` and move LICENSE and README into the addons/better-terrain folder.

And everytime you do a release, just merge it into the release branch

**Comment by univeous** [comment]
I would highly recommend using [gd-plug](https://github.com/imjp94/gd-plug) to manage addons. It will handle this for you and can also track the addon version/etc.

**Comment by salianifo** [comment]
The Godot docs have a recommendation on how to handle this [here](https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html#recommendations). It recommends using a .gitattributes file, and including a copy of the license in the "addons/better-terrain" folder.

.gitattributes file example given:
```
# Normalize line endings for all files that Git considers text files.
* text=auto eol=lf

# Only include the addons folder when downloading from the Asset Library.
/**        export-ignore
/addons    !export-ignore
/addons/** !export-ignore
```

**Comment by Portponky** [comment]
Thanks to @salianifo 's advice, this is now fixed on the asset library.
