### ISSUE TITLE
Feature: Adding contributors section to the README.md file

### ISSUE THREAD

**Issue by Kalyanimhala** [Portponky/better-terrain#51]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/Portponky/better-terrain/assets/147402107/9d36c7ae-1fc3-4a2f-9d64-4dd3900d7174)

**Comment by Kalyanimhala** [comment]
@Portponky Kindly assign me this issue, I want to work on it. Thank You!

**Comment by Portponky** [comment]
No. Git history shows contributors, github shows it at the side.
