### ISSUE TITLE
Corner Tiles Aren't Correct

### ISSUE THREAD

**Issue by nightblade9** [Portponky/better-terrain#54]
Hi,

Thanks for making this plugin, it's quite amazing.

I noticed that inner corner tiles (e.g. L shape) with simpler tilesets (e.g. 3x3 set of tiles only) don't tile correctly. I see that this is the case in your intro video, too, with your 4x4 platformer tiles.

Is there an easy way to make corner tiles draw correctly, instead of using the center/fill tile?

![image](https://github.com/Portponky/better-terrain/assets/31222662/2c153468-4364-473b-a17a-158a775bfe68)

**Comment by Portponky** [comment]
With those tiles, that is the best fit. There isn't a different tile that would fit there better.

Adding in the tiles required to fill the inner corners, and expanding the peering bits to match them correctly, gives a good result:

![Tileset with 4 additional inner corners](https://github.com/Portponky/better-terrain/assets/33663279/c5609f09-6e24-43c9-8e59-c5b6295961b3)

However this tileset also has a lot of situations that aren't handled. A full tileset like this would typically have 47 tiles. Here's a template:

![47 tile template](https://github.com/Portponky/better-terrain/assets/33663279/d856a9ec-74a8-47cf-8c10-2eb9c5507367)

Of course, it's up to you if your game needs every tile.

**Comment by nightblade9** [comment]
Hi,

Thanks for the prompt response. If I understand correctly, that set of 9 outer + 4 inner tiles is sufficient?

May I recommend putting something like this in your readme? I found your plugin via assetlib, and even after watching the video, it's hard to get a simple example working.

**Comment by nightblade9** [comment]
Can you also show the terrain setup for the inner tiles please, like in my screenshot?

**Comment by Portponky** [comment]
> Thanks for the prompt response. If I understand correctly, that set of 9 outer + 4 inner tiles is sufficient? That's similar to what I needed with a different tool that I used for Godot 3.

It can only make terrain from the tiles it has. If the 9 + 4 works for your use case, then do that. It won't handle every possible way neighboring tiles can connect. For example, it can't handle these:

![Examples of missing tiles](https://github.com/Portponky/better-terrain/assets/33663279/6ff7dd75-0ca0-4bba-9d8c-67b1205a92da)

However, it depends on your game whether or not that is a problem. If you want to handle all possible cases, you'll need to make 47 tiles like in the template above. Every game is different, so there's not one correct answer for what the ideal tile setup is. 

> May I recommend putting something like this in your readme? I found your plugin via assetlib, and even after watching the video, it's hard to get a simple example working.

That's a good idea. I should work on updating the documentation with examples of different terrains.

> Can you also show the terrain setup for the inner tiles please, like in my screenshot?

It's visible at the bottom of the image. The peering color is orange.

**Comment by EricDoherty** [comment]
I am having a tough time getting the 47 tileset working.  My bit masking looks to match the template, but as you see my results don't work.  I am using 48x48 sized tiles.
<img width="1362" alt="image" src="https://github.com/Portponky/better-terrain/assets/16713986/6de17253-9359-472e-b14c-b32f32a12519">

**Comment by Portponky** [comment]
Are you using tiles larger than the tileset tile size?

![Size difference](https://github.com/Portponky/better-terrain/assets/33663279/c955d401-d22d-41f5-8fa7-2d294ff4da86)

Using larger tiles is in Godot is a little odd. They might be larger graphically, but they still only take up one cell. If you want stuff to autotile well, ensure that your tiles match the tileset tile size.

**Comment by nightblade9** [comment]
My auto-tiles broke again today and the info in this thread wasn't enough to recover my work. So, attached is a sample tileset and map. I hope this will work as a reference for anyone else who stumbles on it.

Sample: [sample.zip](https://github.com/Portponky/better-terrain/files/14441273/sample.zip)

- The Space Station tileset has a wall (black with purple piping) and a floor (blue tiles)
- Always draw walls as 2x2 thickness or greater, or it looks wrong (due to the use of minimal tiles)
- The floor is a single 1x1 tile. You can wedge it within walls in whatever shapes you want.
