### ISSUE TITLE
Selection tool issue when there are unchecked sources

### ISSUE THREAD

**Issue by EricDoherty** [Portponky/better-terrain#55]
In the image below you see the middle source is unchecked.  I can use the selection tool on tiles from the top source just fine, but when I try to use it on the bottom source's tiles I don't see any blue outline.  If I then re-check the middle source I see the selection which I had tried to make on the bottom source was applied to the middle source instead even though it was unchecked.

<img width="588" alt="image" src="https://github.com/Portponky/better-terrain/assets/16713986/f6bd36e1-10ae-4a64-b23d-eeaf59e5fe82">

**Comment by Portponky** [comment]
Fixed in c5e582464a7ec73b452733284d573c4a44b6977f
Will update the asset lib, but that usually takes a day or so to go through.

**Comment by Portponky** [comment]
Asset library version is updated. This should now be fixed.
