### ISSUE TITLE
anyway to toggle a randomize seed refresh?

### ISSUE THREAD

**Issue by bazsupport** [Portponky/better-terrain#57]
i notice my probability tiles are always in the same spot. i figured they were rolled sometime and was wondering if we can get a way to reset the seed?

![Godot_4 2_WoRrGTqBIH](https://github.com/Portponky/better-terrain/assets/45674197/fb24227d-6509-4763-bcc3-c7a303da7517)

**Comment by Portponky** [comment]
There's a randomize toggle next to the layers drop down. It will make every tile placed re-roll for random placement.

**Comment by bazsupport** [comment]
wow i missed that one! right in front of me haha. i love this plugin man, thanks!
