### ISSUE TITLE
C# wrapper warning CS8632

### ISSUE THREAD

**Issue by Go-Ba** [Portponky/better-terrain#59]
I'm getting warnings for BetterTerrain.cs `CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.`

![image](https://github.com/Portponky/better-terrain/assets/64071930/5620149a-b50d-467e-a1dc-89f359b115f8)

because you've used ? on things that are already nullable by default like `Array<int>? categories = null` where  `Array<int> categories = null` works fine.

this technically *is* a thing you can do with [Nullable contexts](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts) to make these reference types not nullable by default but there's none in the file.

I'm just wondering if I'm missing any context before just removing the `?` from the reference types or if maybe you just weren't familiar with these types already being nullable by default and the `?` being unnecessary.

**Comment by Portponky** [comment]
I'm not very familiar with C#, and some of the wrapper was provided by a contributor. If you can improve it, please open a PR with the changes. Otherwise, I can download the dot net godot and attempt it myself.

**Comment by Portponky** [comment]
Fixed by PR, asset library version was updated. Should be all fixed.
