### ISSUE TITLE
Feature request: option for nearest neighbor filtering on icons

### ISSUE THREAD

**Issue by treacherousfiend** [Portponky/better-terrain#65]
Hi, I just found this plugin, and have been enjoying it quite a bit, but for my current project i'm using tiles that are 8x8px, and they don't look particularly good as icons due to how blurry they are. Considering the fact that you can set icons to whatever you want, and not just tiles, it might be good as an option
![image](https://github.com/Portponky/better-terrain/assets/46549454/6718a188-49a0-462e-834c-dfe294fc1749)
Although honestly, this might be more of a bug report? the tiles in the actual window look sharp even at different sizes, its just the actual terrain categories themselves that do not
![image](https://github.com/Portponky/better-terrain/assets/46549454/bd3d8552-3cbb-46a9-b042-acf44228a16f)
![image](https://github.com/Portponky/better-terrain/assets/46549454/9bae3f78-8faf-4e2e-ac8d-6871dd1cc26f)
![image](https://github.com/Portponky/better-terrain/assets/46549454/747782e4-6642-4008-9094-13f1303112cc)

**Comment by Portponky** [comment]
Looks like a bug. I'll take a look soon.

**Comment by Portponky** [comment]
Fixed, will update the asset lib version.

**Comment by Portponky** [comment]
Asset lib version was accepted a while back, this should now be fixed in all versions.
