### ISSUE TITLE
Solution for correct tiling between different tilemaps?

### ISSUE THREAD

**Issue by mickeyordog** [Portponky/better-terrain#73]
Hello, thanks for the addon. I was wondering if you know of any solution for the following problem:

<img width="868" alt="image" src="https://github.com/Portponky/better-terrain/assets/36612632/ed4f3d23-867a-42aa-8436-f6d79555f138">

Here I have two different tilemaps next to each other. However, the trees obviously don't tile properly between them since terrains only work within one tilemap. 

Is there any way I can get my tree terrain to treat an empty tile in its tilemap as another tree? This way, my different tilemaps would all tile properly with each other as they assume that any empty space they're touching contains another tree, which I will manually ensure by placing a tree in the adjacent tilemap.

If not, do you know of any other way to solve this problem? Thank you.

**Comment by Portponky** [comment]
It depends what your terrains looks like. One option would be to make the tree tile that has trees on all sides the base tree tile (no peering bits used), and then just put peering bits for grass or other tiles where you don't want tree connectors. If you can post an example tileset I can give a visual example.

**Comment by mickeyordog** [comment]
Thanks for the help. Sure, here is the spritesheet for the trees
<img width="546" alt="image" src="https://github.com/Portponky/better-terrain/assets/36612632/0ff72673-cab7-4483-890a-e6745be30e34">

**Comment by mickeyordog** [comment]
Hi @Portponky , were you still able to help with this?

**Comment by Portponky** [comment]
Oh, I meant to post some examples but I have been very sick the last couple weeks. I'll see what I can do tomorrow.

**Comment by Portponky** [comment]
Hi, I'm finally a bit better. The three things I was going to suggest were:

1 - A blank tile which acts like a tree, which is what you have done

2 - Make everything that's not a tree into a category. Make the tree tiles only match in their blank areas against the non-tree category. So this is like inverting the way trees work.

3 - Make the trees match against decorations. Decorations are empty tiles, so they can be used as a way to match against empty space. If you are not using layers, this might work very well.

I was going to do examples but I have been too unwell to manage. Apologies!
