### ISSUE TITLE
Problems Mixing Straight/Diagonal tiles with Decorations

### ISSUE THREAD

**Issue by MaxRabbit** [Portponky/better-terrain#74]
Hi!
First off, a big thanks for making this plugin and publishing it for the rest of us to use. It's wonderful!

Now, down to the issue.

![image](https://github.com/Portponky/better-terrain/assets/47501232/96d5be57-8b40-4a82-b8d5-f13a9c274887)

As you can see above, the tileset I'm using has both decorations and diagonals.
I've set them up as separate terrains in the same category so they can mix.
The problem is that the decorations for the flat surfaces are appearing on the diagonals too (see center example) and vice versa.
I can't find any way to define _diagonal_ decorations or prevent the horizontal decorations from appearing on the diagonal tiles.

Is there any simple solution?

Thanks for your help!
-Rob

**Comment by Portponky** [comment]
It looks like the decorations are matching against the cave tile category. Try making them match against the specific terrain type you want to match against. Perhaps something like this:

**Comment by MaxRabbit** [comment]
Perfect that did the trick.
I'm having so much fun playing with terrain now~

Thanks for your help!
-Rob
