### ISSUE TITLE
Can not to use.

### ISSUE THREAD

**Issue by Abab-bk** [Portponky/better-terrain#78]
This is my code:
![image](https://github.com/Portponky/better-terrain/assets/55276676/9028f21b-5210-476b-8e25-0e0d896c7c16)
I add a error catch in set_cell():
![image](https://github.com/Portponky/better-terrain/assets/55276676/7191f295-1d02-40ec-a032-f9f7814a2a41)
Outputs:
![image](https://github.com/Portponky/better-terrain/assets/55276676/db932ae4-bf5c-4897-ac1b-88ef8b142c45)
In game, nothing is happened.
![image](https://github.com/Portponky/better-terrain/assets/55276676/65d97f6e-a122-4644-bfa6-dd7ecef73c1c)

PS. It`s work fine in editor.
PS2. Godot 4.2.1 Stable.

**Comment by Abab-bk** [comment]
Oddly enough, after I rebooted Godot a few times, the error disappeared.

**Comment by Abab-bk** [comment]
![image](https://github.com/Portponky/better-terrain/assets/55276676/66bb9b3f-e109-4197-a1e3-f658669a10fa)
Yes, no doubt.

**Comment by Portponky** [comment]
Closing, can't reproduce, probably Godot needing restarted after plugins are installed.
