### ISSUE TITLE
Changing terrain by code

### ISSUE THREAD

**Issue by neepsnikeep** [Portponky/better-terrain#82]
Thanks for the great plugin! I want the player to change terrain, and the `TileData.Terrain` does not seem to be used by this plugin. I struggle to use the Terrains I set up in the editor.

I tried this:

		BetterTerrain test = new BetterTerrain(Map);
		test.SetCell(layer, facingTilePosition, (int)newTerrain);
		test.UpdateTerrainCell(layer, facingTilePosition, true);

What am I doing wrong?

**Comment by Portponky** [comment]
Hi, sorry for taking a while to get back to you. It is not clear what the problem is from this code, as it looks correct. Can you provide a more detailed example?

**Comment by neepsnikeep** [comment]
Oooh got it, sorry, the calculation for the newTerrain used the previous terrain and I forgot to use GetCell there instead of tileData.Terrain. Time to refactor!
Thanks for confirming it's not this part of the code.
