### ISSUE TITLE
Question: Where is the data persisted?

### ISSUE THREAD

**Issue by arran-nz** [Portponky/better-terrain#83]
Thanks for the incredible addon!

I'm making changes to a Terrain, updating peering bits etc and I don't see any changes in the git diff.

Here is my `.gitignore`

```
.mono/
data_*/
mono_crash.*.json

build/
.godot/editor
.godot/exported
```

Where is the data saved and, or, should I update my `.gitignore`? 

Thanks!

**Comment by Portponky** [comment]
The better terrain data is stored as metadata inside the tileset. If you have the tileset in a scene, it will be in the scene's .tscn file. If you have the tileset as a separate resource, it'll be in that .tres file. Sometimes the engine is a little bit lazy with saving resource changes, so if you have the tileset as a separate resource, you might need to manually save it from the drop down menu with the resource in the object inspector.

**Comment by arran-nz** [comment]
Thank you @Portponky, that was it! Really appreciate the help, sorry it was so trivial in this case

**Comment by Portponky** [comment]
Not a problem. Glad you are finding the plugin useful.
