### ISSUE TITLE
Need help with a specific type of walls 

### ISSUE THREAD

**Issue by Gr3gorywolf** [Portponky/better-terrain#88]
Hello im using the modern interiors pack (https://limezu.itch.io/moderninteriors) but the walls have a really weird corners and im really confused about how to make them work, the default walls spritesheets is something like this:
![image](https://github.com/Portponky/better-terrain/assets/26353631/b612b9ab-6135-4fcf-9328-90cb27cae180)
I made a custom tileset using tiled for better terrain build, but lo luck, please @Portponky  end with my suffer!
![walls-full](https://github.com/Portponky/better-terrain/assets/26353631/92779e88-a803-474b-aa70-8d5604006c5b)

**Comment by Portponky** [comment]
Hi, do you have an example of the tiles you are working with? The itch link has the free version with different tiles.

**Comment by Gr3gorywolf** [comment]
yes, sure, 
![Room_Builder_3d_walls_32x32](https://github.com/Portponky/better-terrain/assets/26353631/e19cead9-869c-405e-8f3c-e3cce0165ec5)

**Comment by Portponky** [comment]
Hi, this is a very complicated tileset. I'm not sure what tiles are supposed to go where. I had some success by making an internal floor terrain, and then making some 1x2 sized tiles that match against it and their neighbors. Here's a video:

https://github.com/Portponky/better-terrain/assets/33663279/68de78e7-c196-4fea-b4ca-c57f2f201968

Hope this helps.

**Comment by Gr3gorywolf** [comment]
So cool, can you send me the tile sets that you have done?

**Comment by Portponky** [comment]
I don't have them saved, but they are visible in the video I posted.

**Comment by Gr3gorywolf** [comment]
Thank you so much

**Comment by Gr3gorywolf** [comment]
Hey, im trying to implement it on the 4.2 version but no luck, im unable to position the terrain types and connect types properly
![image](https://github.com/user-attachments/assets/af7c55a1-bb29-483d-a7e8-fa8ee88c7d94)

**Comment by Portponky** [comment]
Hi, this issue is closed so it's hard to catch this kind of post. I believe I used 1x2 tiles when I tried this, so I would suggest altering the tileset to make some larger tiles.
