### ISSUE TITLE
Enabling the plugin restarted the editor and discarded my unsaved work

### ISSUE THREAD

**Issue by Macksaur** [Portponky/better-terrain#91]
There's an unconfirmed editor restart when you enable the plugin for the first time and I wasn't prompted to save anything, so I lost some work. Woops.

Love the plugin btw.

**Comment by Portponky** [comment]
Oops, that's not good. I'll fix that up. Sorry!

**Comment by Portponky** [comment]
Added a confirmation popup so restarting is not forced. Will update the assetlib version.

**Comment by Portponky** [comment]
This should be fixed now. Thanks.
