### ISSUE TITLE
Terrain types are not saved upon closing the editor

### ISSUE THREAD

**Issue by gatomesa** [Portponky/better-terrain#97]
Godot v4.2.2.stable - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

Upon closing the editor, any terrain types I create are not saved. Everything is reset to just the default "Decoration" type.
I tested on a fresh project and everything is saved correctly, which means there's something on my project causing it not to save. I would be happy to share any info about my project to help diagnose this.

To start with, here's some info that could be useful:
- I'm doing this on a scene that has a lot of Tilemap nodes (about 150). These tilemaps all share one tileset resource.
- I already have a Terrain Set created, with 7 terrains already created.

**Comment by Portponky** [comment]
Is this a duplicate of #11 which has the workaround described here? https://github.com/Portponky/better-terrain/issues/11#issuecomment-1669183577

**Comment by gatomesa** [comment]
Yes, it seems to be a duplicate, and the workaround mentioned there works, so I'll close this. Thanks for letting me know!
